import "@/styles/globals.css";

import { Nunito } from "next/font/google";

import { TRPCReactProvider } from "@/trpc/react";
import { ThemeProvider } from "@/components/theme-provider";
import { ptBR } from "@clerk/localizations";
import { ClerkProvider } from '@clerk/nextjs'

const fontFamily = Nunito({
  subsets: ["latin"],
});

export const metadata = {
  title: "Encurt.ai",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
        <ClerkProvider appearance={{
            variables: { colorPrimary: '#6d28d9' },
            elements: {
                formButtonPrimary: "#6d28d9"
            }
        }}
        localization={ptBR}>
            <html lang="br">
                <body className={fontFamily.className}>
                    <TRPCReactProvider>
                        <ThemeProvider
                        attribute="class"
                        defaultTheme="system"
                        enableSystem>
                            {children}
                        </ThemeProvider>
                    </TRPCReactProvider>
                </body>
            </html>
        </ClerkProvider>
  );
}
